In [5]:
import pandas as pd

In [7]:
df=pd.read_csv("wcplayerstatistics2018.csv")

In [8]:
df.head(10)

,Rk,Player,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,PKatt,CrdY,CrdR,PlayerID,AstPer90,G+APer90,GlsPer90,G-PKPer90,G+A-PKPer90,SecondPos
0,1,Mohamed Abdel-Shafy,DF,eg Egypt,32,1985,3,3,270,3.0,...,0,0,0,f948de7f,0.0,0.00,0.00,0.00,0.00,NaN
1,2,Shehu Abdullahi,DF,ng Nigeria,25,1993,1,1,90,1.0,...,0,0,0,7ecc9dee,0.0,0.00,0.00,0.00,0.00,NaN
2,3,Johnny Acosta,DF,cr Costa Rica,34,1983,3,3,270,3.0,...,0,1,0,6aaf0284,0.0,0.00,0.00,0.00,0.00,NaN
3,4,Marcos Acuña,MF,ar Argentina,26,1991,1,1,90,1.0,...,0,1,0,81442ecb,0.0,0.00,0.00,0.00,0.00,NaN
4,5,Luis Advíncula,DF,pe Peru,28,1990,3,3,270,3.0,...,0,0,0,cacadf4f,0.0,0.00,0.00,0.00,0.00,NaN
5,6,Sergio Agüero,FW,ar Argentina,30,1988,4,2,179,2.0,...,0,0,0,4d034881,0.0,1.01,1.01,1.01,1.01,NaN
6,7,Abel Aguilar,MF,co Colombia,33,1985,1,1,31,0.3,...,0,0,0,6936b41b,0.0,0.00,0.00,0.00,0.00,NaN
7,8,Karim El Ahmadi,MF,ma Morocco,33,1985,3,3,265,2.9,...,0,2,0,0ff9eabc,0.0,0.00,0.00,0.00,0.00,NaN
8,9,Manuel Akanji,DF,ch Switzerland,22,1995,4,4,360,4.0,...,0,0,0,89ac64a6,0.0,0.00,0.00,0.00,0.00,NaN
9,10,Igor Akinfeev,GK,ru Russia,32,1986,5,5,510,5.7,...,0,0,0,42ec696a,0.0,0.00,0.00,0.00,0.00,NaN

In [9]:
df.tail(10)

,Rk,Player,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,PKatt,CrdY,CrdR,PlayerID,AstPer90,G+APer90,GlsPer90,G-PKPer90,G+A-PKPer90,SecondPos
593,594,Kim Young-gwon,DF,kr Korea Republic,28,1990,3,3,270,3.0,...,0,1,0,9459ace1,0.00,0.33,0.33,0.33,0.33,NaN
594,595,Yun Young-sun,DF,kr Korea Republic,29,1988,1,1,90,1.0,...,0,0,0,3ce8104c,0.00,0.00,0.00,0.00,0.00,NaN
595,596,Denis Zakaria,DF,ch Switzerland,21,1996,2,0,52,0.6,...,0,1,0,384d58d9,1.73,1.73,0.00,0.00,1.73,MF
596,597,Cristián Zapata,DF,co Colombia,31,1986,1,0,5,0.1,...,0,0,0,b1deecf8,0.00,0.00,0.00,0.00,0.00,NaN
597,598,Yuri Zhirkov,DF,ru Russia,34,1983,3,3,220,2.4,...,0,0,0,ed2b33cb,0.00,0.00,0.00,0.00,0.00,NaN
598,599,Piotr Zieliński,FW,pl Poland,24,1994,3,3,258,2.9,...,0,0,0,a5296e55,0.00,0.00,0.00,0.00,0.00,MF
599,600,Andrija Živković,FW,rs Serbia,21,1996,1,0,16,0.2,...,0,0,0,321f83a2,0.00,0.00,0.00,0.00,0.00,MF
600,601,Hakim Ziyech,MF,ma Morocco,25,1993,3,3,264,2.9,...,0,0,0,6622454d,0.00,0.00,0.00,0.00,0.00,NaN
601,602,Roman Zobnin,MF,ru Russia,24,1994,5,5,510,5.7,...,0,1,0,0a215326,0.18,0.18,0.00,0.00,0.18,NaN
602,603,Steven Zuber,MF,ch Switzerland,26,1991,3,3,251,2.8,...,0,0,0,b6a6e0a7,0.00,0.36,0.36,0.36,0.36,NaN

In [12]:
df.shape[0]

603

In [13]:
df.columns

Index(['Rk', 'Player', 'Pos', 'Squad', 'Age', 'Born', 'MP', 'Starts', 'Min',
       '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR',
       'PlayerID', 'AstPer90', 'G+APer90', 'GlsPer90', 'G-PKPer90',
       'G+A-PKPer90', 'SecondPos'],
      dtype='str')

In [15]:
df.isnull().sum()

Rk               0
Player           0
Pos              0
Squad            0
Age              0
Born             0
MP               0
Starts           0
Min              0
90s              0
Gls              0
Ast              0
G+A              0
G-PK             0
PK               0
PKatt            0
CrdY             0
CrdR             0
PlayerID         0
AstPer90         0
G+APer90         0
GlsPer90         0
G-PKPer90        0
G+A-PKPer90      0
SecondPos      518
dtype: int64

In [18]:
print("avg goal",df["Gls"].mean())

avg goal 0.2603648424543947

In [19]:
print("minimum goal",df["Gls"].min())

minimum goal 0

In [20]:
print("maximum goal",df["Gls"].max())

maximum goal 6

In [21]:
df.groupby("Squad").size()

Squad
ar Argentina         20
au Australia         15
be Belgium           21
br Brazil            18
ch Switzerland       17
co Colombia          20
cr Costa Rica        20
de Germany           20
dk Denmark           20
eg Egypt             16
eng England          21
es Spain             17
fr France            21
hr Croatia           21
ir IR Iran           16
is Iceland           17
jp Japan             18
kr Korea Republic    19
ma Morocco           19
mx Mexico            19
ng Nigeria           16
pa Panama            20
pe Peru              17
pl Poland            21
pt Portugal          18
rs Serbia            18
ru Russia            19
sa Saudi Arabia      20
se Sweden            19
sn Senegal           18
tn Tunisia           23
uy Uruguay           19
dtype: int64

In [24]:
df.groupby("Pos")["Player"].size()

Pos
DF    196
FW    130
GK     40
MF    237
Name: Player, dtype: int64

In [26]:
df.groupby("Squad")["Gls"].mean()

Squad
ar Argentina         0.300000
au Australia         0.133333
be Belgium           0.714286
br Brazil            0.444444
ch Switzerland       0.294118
co Colombia          0.300000
cr Costa Rica        0.050000
de Germany           0.100000
dk Denmark           0.150000
eg Egypt             0.125000
eng England          0.571429
es Spain             0.352941
fr France            0.571429
hr Croatia           0.619048
ir IR Iran           0.062500
is Iceland           0.117647
jp Japan             0.333333
kr Korea Republic    0.157895
ma Morocco           0.105263
mx Mexico            0.157895
ng Nigeria           0.187500
pa Panama            0.050000
pe Peru              0.117647
pl Poland            0.095238
pt Portugal          0.333333
rs Serbia            0.111111
ru Russia            0.526316
sa Saudi Arabia      0.100000
se Sweden            0.263158
sn Senegal           0.166667
tn Tunisia           0.217391
uy Uruguay           0.315789
Name: Gls, dtype: float64

In [32]:
df[df["Age"]>36]

,Rk,Player,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,PKatt,CrdY,CrdR,PlayerID,AstPer90,G+APer90,GlsPer90,G-PKPer90,G+A-PKPer90,SecondPos
44,45,Felipe Baloy,DF,pa Panama,37,1981,1,0,22,0.2,...,0,0,0,2229d417,0.0,4.09,4.09,4.09,4.09,NaN
88,89,Tim Cahill,FW,au Australia,38,1979,1,0,38,0.4,...,0,0,0,e5a2dfc2,0.0,0.00,0.00,0.00,0.00,MF
217,218,Essam El-Hadary,GK,eg Egypt,45,1973,1,1,90,1.0,...,0,0,0,79307650,0.0,0.00,0.00,0.00,0.00,NaN
250,251,Sergei Ignashevich,DF,ru Russia,38,1979,5,5,510,5.7,...,0,0,0,04f2ed4d,0.0,0.00,0.00,0.00,0.00,NaN
349,350,Rafael Márquez,MF,mx Mexico,39,1979,3,1,86,1.0,...,0,0,0,ce067ffe,0.0,0.00,0.00,0.00,0.00,NaN
433,434,Blas Pérez,FW,pa Panama,37,1981,2,2,162,1.8,...,0,0,0,b9c81163,0.0,0.00,0.00,0.00,0.00,NaN

In [34]:
goalavg=(df["Gls"].mean())*100
print("goals %",goalavg)

goals % 26.036484245439468

In [35]:
df.groupby("Pos")["G+A"].sum()

Pos
DF     45
FW     85
GK      0
MF    133
Name: G+A, dtype: int64

In [36]:
print(df["G+A"].mean())

0.4361525704809287

In [38]:
print(df["G+A"].std())

0.9116192322039463

In [39]:
print(df["G+A"].min())

0

In [40]:
print(df["G+A"].max())

6

In [47]:
df["SecondPos"] = df["SecondPos"].fillna("Unknown")
df["SecondPos"].isnull().sum()

np.int64(0)

In [49]:
df=df.drop_duplicates()
df.to_csv("wc2018_cleaned.csv", index=False)